spring:
  application:
    name: securityTest
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test_collect?
    username: collector
    password: 6382
  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
#server:
#  ssl:
#    key-store-type: PKCS12
#    key-store: ./certificate.p12
#    key-store-password: 6382
